name: 'Test tasks/b/arithmetics.py'

on:
  pull_request:
    types: [ opened, edited, synchronize ]
    paths:
      - 'tasks/b/arithmetics.py'
      - 'test/b/test_arithmetics.py'
      - '.github/workflows/b-arithmetics.yaml'
  workflow_dispatch:

jobs:
  test-arithmetics:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    strategy:
      fail-fast: false
      matrix:
        line: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install pytest
      - run: pytest test/b/test_arithmetics.py::test_arithmetics --line ${{ matrix.line }}
  test-floats-count:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install pytest
      - run: pytest test/b/test_arithmetics.py::test_floats_count