name: 'Test tasks/b/data.py'

on:
  pull_request:
    types: [ opened, edited, synchronize ]
    paths:
      - 'tasks/b/data.py'
      - 'test/b/test_data.py'
      - '.github/workflows/b-data.yaml'
  workflow_dispatch:

jobs:
  test-data:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    strategy:
      fail-fast: false
      matrix:
        line: [ 1, 2, 3, 4, 5, 6, 7, 8 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install pytest
      - run: pytest test/b/test_data.py --line ${{ matrix.line }}